# **MÓDULO 20 - Projeto de Credit Score - Naive Bayes**

No módulo 17 vocês realizaram a primeira etapa do projeto de crédito de vocês.
Então fizeram o tratamendo dos dados, balancearam as classes, transformaram as variáveis categóricas e separam base de treino e teste.
Nessa aula aplicaremos o algoritmo de naive bayes a base de vocês afim de tentarmos trazer previsões do score de crédito.

**IMPORTANTE:** Não se esqueçam de ao enviar o código de vocês para os tutores, enviarem as bases, pois como cada um de vocês realizou as alterações de tratamento indidualmente o tutor precisa ter acesso aos seus dados individuais.

In [16]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score

Durante a aula nossa variável a ser prevista (churn) continha apenas 2 categorias, a base de vocês contém mais. O Naive Bayes pode ser aplicado para problemas de classificação com múltiplas classes da mesma forma que para problemas de classificação binária. O Naive Bayes é um algoritmo de classificação probabilístico que calcula a probabilidade de uma amostra pertencer a cada classe e seleciona a classe com a maior probabilidade como a previsão final.
Em resumo, o Naive Bayes pode ser aplicado da mesma maneira para problemas de classificação com múltiplas classes, e os mesmos princípios se aplicam em termos de treinamento, avaliação e aplicação do modelo.

# 1) Comece carregando as bases de treino (X e y) e teste (X e y).
Verifique se o número de linhas condiz, se as variáveis estão corretas sendo apenas a de score para y e as demais nas bases de X e por último, se Y está balanceada no teste.

In [3]:
#seu código aqui
X_test = pd.read_csv("X_test_cs.csv", delimiter=',')
X_train = pd.read_csv("X_train_balanced_cs.csv", delimiter=',')
y_test = pd.read_csv("y_test_cs.csv", delimiter=',')
y_train = pd.read_csv("y_train_balanced_cs.csv", delimiter=',')

In [4]:
X_train

,Age,Income,Number of Children,Gender_Male,Education_encoded,Marital Status_Single,Home Ownership_Rented
0,26,45000.000000,0,0,0,1,1
1,29,27500.000000,0,0,3,1,1
2,25,62500.000000,0,0,1,1,1
3,29,68000.000000,2,0,2,0,0
4,31,65000.000000,0,1,1,1,1
...,...,...,...,...,...,...,...
247,29,43703.466973,0,0,0,1,1
248,34,47500.000000,0,1,0,1,1
249,29,57500.000000,0,0,0,1,1
250,25,60063.547817,0,0,1,1,1
251,33,52500.000000,0,1,3,1,1

In [5]:
y_train

     Credit Score_ordinal_encoded
0                               1
1                               0
2                               1
3                               1
4                               1
..                            ...
247                             1
248                             1
249                             1
250                             1
251                             1

[252 rows x 1 columns]

In [6]:
X_test

,Age,Income,Number of Children,Gender_Male,Education_encoded,Marital Status_Single,Home Ownership_Rented
0,25,55000.0,0,0,1,1,1
1,48,87500.0,1,0,2,0,0
2,26,55000.0,1,0,1,0,0
3,39,62500.0,2,0,1,0,0
4,35,90000.0,1,0,2,0,0
5,25,55000.0,0,0,1,1,1
6,48,82500.0,1,0,2,0,0
7,48,82500.0,1,0,2,0,0
8,36,95000.0,2,0,4,0,0
9,36,95000.0,1,0,3,0,0
10,36,50000.0,0,1,3,1,1
11,36,27500.0,0,0,3,1,1
12,36,95000.0,0,1,4,1,0
13,50,160000.0,0,1,4,0,0
14,29,25000.0,0,0,3,1,1
15,30,105000.0,2,1,4,0,0
16,32,85000.0,0,1,4,1,1
17,27,37500.0,0,0,3,1,1
18,36,130000.0,0,1,3,0,0
19,36,85000.0,1,0,2,0,0
20,37,75000.0,2,0,1,0,0
21,36,30000.0,0,0,0,1,1
22,36,35000.0,0,0,3,1,1
23,36,105000.0,0,1,2,1,0
24,35,80000.0,1,0,2,0,0
25,38,67500.0,2,0,1,0,0
26,50,162500.0,0,1,4,0,0
27,44,87500.0,0,1,4,1,0
28,34,105000.0,1,1,1,0,1
29,34,47500.0,0,1,0,1,1
30,45,105000.0,3,0,1,0,0
31,52,135000.0,0,1,3,0,0
32,35,85000.0,1,0,2,0,0
33,36,125000.0,0,1,0,0,0
34,35,75000.0,1,0,2,0,0
35,30,117500.0,2,1,4,0,0
36,47,90000.0,1,0,2,0,0
37,32,57500.0,0,1,0,1,1
38,36,90000.0,2,0,4,0,0
39,28,32500.0,0,0,0,1,1
40,39,60000.0,2,0,1,0,0

In [7]:
y_test

    Credit Score_ordinal_encoded
0                              1
1                              2
2                              1
3                              2
4                              2
5                              1
6                              2
7                              2
8                              2
9                              2
10                             1
11                             0
12                             2
13                             2
14                             0
15                             2
16                             2
17                             0
18                             2
19                             2
20                             2
21                             0
22                             0
23                             2
24                             2
25                             2
26                             2
27                             2
28                             2
29                             1
30                             2
31                             2
32                             2
33                             2
34                             2
35                             2
36                             2
37                             1
38                             2
39                             0
40                             2

In [8]:
# Contar o número de exemplos de cada classe em y_train
train_balance = y_train.value_counts()
print("Balanceamento em y_train:")
print(train_balance)

# Contar o número de exemplos de cada classe em y_test
test_balance = y_test.value_counts()
print("\nBalanceamento em y_test:")
print(test_balance)

Balanceamento em y_train:
Credit Score_ordinal_encoded
0                               84
1                               84
2                               84
Name: count, dtype: int64

Balanceamento em y_test:
Credit Score_ordinal_encoded
2                               29
0                                6
1                                6
Name: count, dtype: int64

# 2) Aplique o algoritmo de Naive Bayes aos dados de treinamento.

In [9]:
#seu código aqui
naive_churn = GaussianNB()
naive_churn.fit(X_train, y_train)

C:\Users\João\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GaussianNB()

# 3) Faça a avaliação do modelo com os dados de treinamento.
Traga a acurácia, recall e plote a matriz de confusão. Não se esqueça de avaliar com suas palavras o desempenho do modelo, interpretando as métricas.

Dica: Para calcularmos o recall em classificação multi classe precisamos usar o atributo macro:
recall = recall_score(y_train, y_pred_train, average='macro')

In [10]:
#seu código aqui
y_pred_train = naive_churn.predict(X_train)

accuracy = accuracy_score(y_train, y_pred_train)
print("Acurácia:", accuracy)

Acurácia: 0.9801587301587301

In [11]:
recall = recall_score(y_train, y_pred_train, average='macro')
print("Recall:", recall)

Recall: 0.9801587301587302

In [18]:
conf_matrix = confusion_matrix(y_train, y_pred_train)

conf_matrix

array([[82,  2,  0],
       [ 1, 83,  0],
       [ 0,  2, 82]], dtype=int64)

In [ ]:
# O modelo com a base treino apresentou um nível de acurácia e recall muito altos, indicando que o modelo está fazendo previsões corretas em aproximadamente 98% dos exemplos no conjunto de dados. Fato que é corroborado quando analisamos a matriz de confusão.

# 4) Aplique o modelo aos dados de teste e realize a avaliação dos resultados, da mesma forma que fez acima. Não se esqueça de avaliar com as suas palavras e comparar o desempenho da base treino com a teste.

In [12]:
#seu código aqui
y_pred_test = naive_churn.predict(X_test)

accuracy = accuracy_score(y_test, y_pred_test)
print("Acurácia:", accuracy)

Acurácia: 0.975609756097561

In [13]:
recall = recall_score(y_test, y_pred_test, average='macro')
print("Recall:", recall)

Recall: 0.9444444444444445

In [19]:
conf_matrix = confusion_matrix(y_test, y_pred_test)

conf_matrix

array([[ 5,  1,  0],
       [ 0,  6,  0],
       [ 0,  0, 29]], dtype=int64)

In [ ]:
# Na base de teste o modelo também conseguiu um alto nível de acurácia e recall. Estes valores são inferiores aos encontrados na base de treino, porém, ao analisar a matriz de confusão, observa-se que houve apenas um erro que, por a base ser pequena, fez com obtivesse esse resultado inferior.

# 5) Descreva com suas palavras o projeto desenvolvido nessa atividade e qual o nosso objetivo principal ao aplicarmos o algoritmo de naive bayes a base de crédito.
Neste projeto, aplicamos o algoritmo de Naive Bayes a uma base de crédito com o objetivo de prever corretamente o score dos clientes. Inicialmente, carregamos as bases de treino e teste, conferindo se os dados estavam organizados corretamente e se a base de teste estava balanceada.

Após treinar o modelo, obtivemos uma acurácia e recall de 0,98 na base de treino. Já na base de teste, os resultados foram também muito bons, com acurácia de 0,975 e recall de 0,944. A matriz de confusão mostrou apenas um erro de classificação na base de teste, o que explica a leve diferença de desempenho.

De forma geral, o modelo se mostrou eficiente, com bom desempenho tanto no treino quanto no teste, o que indica uma boa capacidade de generalização.